#!/bin/bash

args=("$@")
if [[ ${#args[@]} -lt 1 ]]; then
        echo "At least 1 argument is required"
        exit 1
fi
jobname=${args[0]}
JOBID=$(sacct -s RUNNING -o jobid,jobname -P -n --delimiter ';' | grep "${jobname}" | cut -d';' -f 1)
scancel ${JOBID} || true